- name: Install nginx
  dnf:
    name: nginx
    state: present
    use_backend: dnf4
  tags: [nginx-install, install]

- name: Create directory for nginx SELinux policy modules
  file:
    path: "{{nginx_selinux_policy_dir}}"
    state: directory
    owner: root
    group: root
    mode: u=rwx,g=rx,o=rx

- name: Copy nginx-allow-use-sockets SELinux policy module
  copy:
    src: "files/nginx-allow-use-sockets.te"
    dest: "{{nginx_selinux_policy_dir}}/nginx-allow-use-sockets.te"
    mode: u=rw,g=r,o=r
  notify: "Install nginx-allow-use-sockets SELinux policy module"

- name: Set nginx default config
  template:
    src: templates/config/nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    mode: u=rw,g=r,o=r
  notify: Restart nginx
