- name: Install uWSGI and its Python plugin
  dnf:
    name:
      - "uwsgi"
      - "uwsgi-plugin-{{uwsgi_python_plugin}}"
    state: present
    use_backend: dnf4
  tags: [uwsgi-install, install]

- name: Enable and start uWSGI
  systemd_service:
    name: uwsgi
    state: started
    enabled: true
