- name: Common changes for all servers
  import_playbook: site-common.yml
- name: Database servers
  import_playbook: site-database.yml
- name: Worker servers
  import_playbook: site-worker.yml
- name: Web servers
  import_playbook: site-web.yml
- name: Backup servers
  import_playbook: site-backup.yml
