- name: Apply SELinux context to uWSGI socket directory
  command: "restorecon -Rv {{passari_web_ui_uwsgi_socket_dir}}"
  register: sockdir_restorecon_res
  changed_when: sockdir_restorecon_res.stdout or sockdir_restorecon_res.stderr

- name: Check if Let's Encrypt SSL certificate is available
  stat:
    path: "{{letsencrypt_cert_path}}"
  register: ssl_certificate_dir
  listen: Regenerate Passari Web nginx config and restart nginx

- name: Update passari_web_ui.conf nginx config
  template:
    src: "templates/config/passari_web_ui_nginx.conf.j2"
    dest: "/etc/nginx/conf.d/passari_web_ui.conf"
    mode: u=rw,g=r,o=r
  listen: Regenerate Passari Web nginx config and restart nginx

- name: Restart nginx after updating passari_web_ui.conf
  systemd_service:
    name: nginx
    state: restarted
  listen: Regenerate Passari Web nginx config and restart nginx
