# Pass some shared variables to the roles

letsencrypt_site_domain: "{{site_domain}}"
passari_web_ui_site_domain: "{{site_domain}}"

passari_backup_db_name: "{{db_name}}"
passari_backup_db_superuser: "{{db_superuser}}"
passari_backup_db_superuser_password: "{{db_superuser_password}}"
passari_backup_db_hostname: "{{db_hostname}}"
passari_backup_db_port: "{{db_port}}"
passari_backup_db_password: "{{db_backup_user_password}}"

postgresql_db_name: "{{db_name}}"
postgresql_db_user: "{{db_user}}"
postgresql_db_password: "{{db_password}}"

passari_workflow_db_url: "{{db_url}}"
passari_workflow_redis_url: "{{redis_url}}"

uwsgi_python_version: "{{passari_packages_python_version}}"

passari_web_ui_heartbeat_interval_sync_objects: >-
  {{sync_objects_interval}}
passari_web_ui_heartbeat_interval_sync_attachments: >-
  {{sync_attachments_interval}}
passari_web_ui_heartbeat_interval_sync_processed_sips: >-
  {{sync_processed_sips_interval}}
passari_web_ui_heartbeat_interval_sync_hashes: >-
  {{sync_hashes_interval}}
