- name: Install zstd for backup compression
  dnf:
    name: zstd
    state: present
    use_backend: dnf4
  tags: [passari-backup-install, install]

- name: Create backup user
  user:
    name: "{{passari_backup_user}}"
    home: "{{passari_backup_home}}"

- name: Create PostgreSQL backup user
  community.postgresql.postgresql_user:
    name: "{{passari_backup_db_user}}"
    password: "{{passari_backup_db_password}}"
    db: "{{passari_backup_db_name}}"
    encrypted: true
    login_host: "{{passari_backup_db_hostname}}"
    login_user: "{{passari_backup_db_superuser}}"
    login_password: "{{passari_backup_db_superuser_password}}"
  become: true
  become_user: postgres
  when: passari_backup_db_user

- name: Grant privileges to PostgreSQL backup user
  community.postgresql.postgresql_privs:
    db: "{{passari_backup_db_name}}"
    role: "{{passari_backup_db_user}}"
    objs: "{{item.objs}}"
    privs: "{{item.privs}}"
    type: "{{item.type}}"
    login_host: "{{passari_backup_db_hostname}}"
    login_user: "{{passari_backup_db_superuser}}"
    login_password: "{{passari_backup_db_superuser_password}}"
  loop:
    - {type: "table", objs: "ALL_IN_SCHEMA", privs: "SELECT"}
    - {type: "sequence", objs: "ALL_IN_SCHEMA", privs: "SELECT"}
    - {type: "database", objs: null, privs: "CONNECT"}
  become: true
  become_user: postgres
  when: passari_backup_db_user

- name: Create pgpass file
  template:
    src: templates/pgpass.j2
    dest: "{{passari_backup_home}}/.pgpass"
    owner: "{{passari_backup_user}}"
    group: "{{passari_backup_user}}"
    mode: u=rw,g=,o=
  when: passari_backup_db_user and passari_backup_db_password

- name: Create backup directory
  file:
    path: "{{passari_backup_dir}}"
    state: directory
    owner: "{{passari_backup_user}}"
    group: "{{passari_backup_user}}"
    mode: u=rwx,g=rx,o=

- name: Create PostgreSQL backup script
  template:
    src: templates/backup-passari-db.sh.j2
    dest: "{{passari_backup_script_path}}"
    mode: u=rwx,g=rx,o=rx

- name: Create backup service
  template:
    src: templates/backup-passari-db.service.j2
    dest: "/etc/systemd/system/backup-passari-db.service"
    mode: u=rw,g=r,o=r
  notify: Reload systemd daemon

- name: Create backup timer
  template:
    src: templates/backup-passari-db.timer.j2
    dest: "/etc/systemd/system/backup-passari-db.timer"
    mode: u=rw,g=r,o=r
  notify: Reload systemd daemon

- name: Flush notify handlers to get systemd reload now (if needed)
  meta: flush_handlers

- name: Enable automatic PostgreSQL backups
  systemd:
    name: backup-passari-db.timer
    enabled: true
    state: started
