---
- name: Install dependencies
  yum:
    name:
      - postgresql-devel
      - python3-devel
  tags: museumplus-pas-workflow

- name: Clone museumplus-pas-workflow
  git:
    repo: git@museopas-gitlab.northeurope.cloudapp.azure.com:museumplus-pas/museumplus-pas-workflow.git
    dest: "{{ museumplus_pas_workflow_install_path }}"
    version: "{{ museumplus_pas_workflow_version }}"
    key_file: "{{ museumplus_pas_home }}/.ssh/id_git_deploy"
  become_user: "{{ museumplus_pas_user }}"
  tags: museumplus-pas-workflow

- name: Install museumplus-pas-workflow
  pip:
    chdir: "{{ museumplus_pas_workflow_install_path }}"
    virtualenv: ".venv"
    virtualenv_python: python3.6
    name: .
  become_user: "{{ museumplus_pas_user }}"
  tags: museumplus-pas-workflow

# museumplus-pas is required in order to enqueue tasks
- name: Clone museumplus-pas
  git:
    repo: git@museopas-gitlab.northeurope.cloudapp.azure.com:museumplus-pas/museumplus-pas.git
    dest: "{{ museumplus_pas_install_path }}"
    version: "{{ museumplus_pas_version }}"
    key_file: "{{ museumplus_pas_home }}/.ssh/id_git_deploy"
  become_user: "{{ museumplus_pas_user }}"
  tags: museumplus-pas-workflow

- name: Install museumplus-pas
  pip:
    chdir: "{{ museumplus_pas_install_path }}"
    virtualenv: "{{ museumplus_pas_workflow_install_path }}/.venv"
    virtualenv_python: python3.6
    name: .
  become_user: "{{ museumplus_pas_user }}"
  tags: museumplus-pas-workflow

- name: Install run-venv.sh
  template:
    src: "templates/scripts/run-venv.sh.j2"
    dest: "{{ museumplus_pas_workflow_install_path }}/run-venv.sh"
    mode: u=rwx,g=rx,o=rx
  become_user: "{{ museumplus_pas_user }}"
  tags: museumplus-pas-workflow

- name: Create museumplus-pas configuration directory
  file:
    path: "/etc/museumplus-pas"
    state: directory
  tags: museumplus-pas-workflow

- name: Create museumplus-pas configuration file
  template:
    src: "templates/config/museumplus-pas.config.toml.j2"
    dest: "/etc/museumplus-pas/config.toml"
  tags: museumplus-pas-workflow

- name: Create museumplus-pas-workflow configuration directory
  file:
    path: "/etc/museumplus-pas-workflow"
    state: directory
  tags: museumplus-pas-workflow

- name: Copy museumplus-pas-workflow configuration file
  template:
    src: "templates/config/museumplus-pas-workflow.config.toml.j2"
    dest: "/etc/museumplus-pas-workflow/config.toml"
  tags: museumplus-pas-workflow

- name: Create workflow object directory
  file:
    path: "{{ workflow_package_dir }}"
    state: directory
  become_user: "{{ museumplus_pas_user }}"
  tags: museumplus-pas-workflow

- name: Create workflow archive directory
  file:
    path: "{{ workflow_archive_dir }}"
    state: directory
  become_user: "{{ museumplus_pas_user }}"
  tags: museumplus-pas-workflow

- name: Run database migrations
  command: "./run-venv.sh alembic upgrade head"
  args:
    chdir: "{{ museumplus_pas_workflow_install_path }}"
  become_user: "{{ museumplus_pas_user }}"
  tags: museumplus-pas-workflow

- name: Create synchronization service files
  template:
    src: "templates/config/{{ item }}.service.j2"
    dest: "/etc/systemd/system/{{ item }}.service"
  loop:
    - "sync-attachments"
    - "sync-objects"
    - "sync-hashes"
    - "sync-processed-sips"
    - "stop-sync-attachments"
    - "stop-sync-objects"
  tags: museumplus-pas-workflow

- name: Create synchronization timer files
  template:
    src: "templates/config/{{ item }}.timer.j2"
    dest: "/etc/systemd/system/{{ item }}.timer"
  loop:
    - "sync-attachments"
    - "sync-objects"
    - "sync-hashes"
    - "sync-processed-sips"
    - "stop-sync-attachments"
    - "stop-sync-objects"
  tags: museumplus-pas-workflow

- name: Create worker configuration file
  template:
    src: templates/config/worker_config.py.j2
    dest: "{{ museumplus_pas_workflow_install_path }}/worker_config.py"
  become_user: "{{ museumplus_pas_user }}"
  tags: museumplus-pas-workflow

- name: Create worker scripts
  template:
    src: templates/scripts/{{ item }}-worker.sh.j2
    dest: "{{ museumplus_pas_workflow_install_path }}/{{ item }}-worker.sh"
    mode: "u=rwx,g=rx,o=rx"
  become_user: "{{ museumplus_pas_user }}"
  loop:
    - "download-object"
    - "create-sip"
    - "submit-sip"
    - "confirm-sip"
  tags: museumplus-pas-workflow

- name: Create worker services
  template:
    src: "templates/config/{{ item }}-worker@.service.j2"
    dest: "/etc/systemd/system/{{ item }}-worker@.service"
  loop:
    - "download-object"
    - "stop-download-object"
    - "create-sip"
    - "submit-sip"
    - "confirm-sip"
  tags: museumplus-pas-workflow

- name: Create worker timers
  template:
    src: "templates/config/{{ item }}-worker@.timer.j2"
    dest: "/etc/systemd/system/{{ item }}-worker@.timer"
  loop:
    - "download-object"
    - "stop-download-object"
  tags: museumplus-pas-workflow

- name: Reload systemd daemon
  systemd:
    daemon_reload: true
  tags: museumplus-pas-workflow

- name: Enable automated startup for sync-objects
  systemd:
    name: "{{ item }}.timer"
    state: "{% if enable_sync_objects %}started{% else %}stopped{% endif %}"
    enabled: "{{ enable_sync_objects }}"
  loop:
    - "sync-objects"
    - "stop-sync-objects"
  tags: museumplus-pas-workflow

- name: Enable automated startup for sync-attachments
  systemd:
    name: "{{ item }}.timer"
    state: "{% if enable_sync_attachments %}started{% else %}stopped{% endif %}"
    enabled: "{{ enable_sync_attachments }}"
  loop:
    - "sync-attachments"
    - "stop-sync-attachments"
  tags: museumplus-pas-workflow

- name: Enable automated startup for sync-hashes
  systemd:
    name: "sync-hashes.timer"
    state: "{% if enable_sync_hashes %}started{% else %}stopped{% endif %}"
    enabled: "{{ enable_sync_hashes }}"
  tags: museumplus-pas-workflow

- name: Enable automate startup for sync-processed-sips
  systemd:
    name: "sync-processed-sips.timer"
    state: "{% if enable_sync_processed_sips %}started{% else %}stopped{% endif %}"
    enabled: "{{ enable_sync_processed_sips }}"
  tags: museumplus-pas-workflow

- name: Stop workers
  command: "systemctl stop {{ item }}-worker@*"
  loop:
    - "download-object"
    - "create-sip"
    - "submit-sip"
    - "confirm-sip"
  tags: museumplus-pas-workflow

- name: Disable workers
  command: "systemctl disable {{ item }}-worker@*"
  loop:
    - "download-object"
    - "create-sip"
    - "submit-sip"
    - "confirm-sip"
  tags: museumplus-pas-workflow

- name: Enable and start download-object workers
  systemd:
    name: "download-object-worker@{{ item }}.service"
    state: restarted
    enabled: true
  loop: "{{ range(0, worker_count['download_object']) | list }}"
  when: not enable_scheduled_download_objects
  tags: museumplus-pas-workflow

# It's necessary to disable the service itself if a deployment moves
# from having the service enabled to having it enabled on certain times
- name: Disable download-object worker
  systemd:
    name: "download-object-worker@{{ item }}.service"
    enabled: false
  loop: "{{ range(0, worker_count['download_object']) | list }}"
  when: enable_scheduled_download_objects
  tags: museumplus-pas-workflow

- name: Enable download-object timer
  systemd:
    name: "download-object-worker@{{ item }}.timer"
    state: "{% if enable_scheduled_download_objects %}started{% else %}stopped{% endif %}"
    enabled: "{{ enable_scheduled_download_objects }}"
  loop: "{{ range(0, worker_count['download_object']) | list }}"
  tags: museumplus-pas-workflow

- name: Enable stop-download-object timer
  systemd:
    name: "stop-download-object-worker@{{ item }}.timer"
    state: "{% if enable_scheduled_download_objects %}started{% else %}stopped{% endif %}"
    enabled: "{{ enable_scheduled_download_objects }}"
  loop: "{{ range(0, worker_count['download_object']) | list }}"
  tags: museumplus-pas-workflow

- name: Enable and start create-sip workers
  systemd:
    name: "create-sip-worker@{{ item }}"
    state: restarted
    enabled: true
  loop: "{{ range(0, worker_count['create_sip']) | list }}"
  tags: museumplus-pas-workflow

- name: Enable and start submit-sip workers
  systemd:
    name: "submit-sip-worker@{{ item }}"
    state: restarted
    enabled: true
  loop: "{{ range(0, worker_count['submit_sip']) | list }}"
  tags: museumplus-pas-workflow

- name: Enable and start confirm-sip workers
  systemd:
    name: "confirm-sip-worker@{{ item }}"
    state: restarted
    enabled: true
  loop: "{{ range(0, worker_count['confirm_sip']) | list }}"
  tags: museumplus-pas-workflow
