- name: Restart systemd-journald
  systemd_service:
    name: systemd-journald
    state: restarted

- name: Commit initial etc changes
  command:
    cmd: "etckeeper commit Init"
    chdir: /etc
  register: etckeeper_commit_result
  changed_when: "'nothing to commit' not in etckeeper_commit_result.stdout"
