- name: Install GPG key for PAS-jakelu repository
  rpm_key:
    key: "https://pas-jakelu.csc.fi/RPM-GPG-KEY-pas-support-el9"
    state: present

- name: Add PAS-jakelu repository
  command:
    cmd: "dnf config-manager --add-repo={{pas_repo_url}}"
    creates: /etc/yum.repos.d/pas-jakelu-csc-fi.repo
  vars:
    pas_repo_url: "https://pas-jakelu.csc.fi/pas-jakelu-csc-fi.repo"

- name: Install RPM fusion repository
  command:
    cmd: "dnf install -y --nogpgcheck {{url}}"
    creates: /etc/yum.repos.d/rpmfusion-free-updates.repo
  vars:
    base_url: "https://mirrors.rpmfusion.org/free/el"
    pkg_name: "rpmfusion-free-release-9"
    url: "{{base_url}}/{{pkg_name}}.noarch.rpm"
  tags: [validators-install, rpmfusion-install, install]

- name: Install siptools etc. from PAS-jakelu repository
  dnf:
    name:
      - python3-file-scraper-full
      - python3-dpres-siptools
    state: present
    use_backend: dnf4
  tags: [validators-install, siptools-install, install]

# Note: siptools Python packages are installed in passari-workflow role
