- name: Update all packages  # noqa: package-latest
  dnf:
    name: "*"
    state: latest
    use_backend: dnf4
  tags: [common-update, update]

- name: Enable EPEL software repository
  dnf:
    name: epel-release
    use_backend: dnf4

- name: Install important packages
  dnf:
    name:
      - etckeeper
      - sudo
      - firewalld  # Required for ansible.posix.firewalld
      - python3-firewall  # Required for ansible.posix.firewalld
      - python3-policycoreutils  # Required for sefcontext
      - rsync  # Required for ansible.posix.synchronize
    use_backend: dnf4
  tags: [common-packages, common-install, install, sudo, etckeeper]

- name: Initialize etckeeper
  command: etckeeper init
  args:
    chdir: /etc
    creates: /etc/.etckeeper
  notify: Commit initial etc changes
  tags: etckeeper

- name: Flush handlers to commit etckeeper changes
  meta: flush_handlers
  tags: etckeeper

- name: Create /var/log/journal to enable persistent logging
  file:
    path: "/var/log/journal"
    state: directory
    owner: root
    group: systemd-journal
    mode: u=rwx,g=rxs,o=rx
  notify: Restart systemd-journald
  when: has_systemd_journald is not defined or has_systemd_journald
