passari_web_ui_site_domain: "{{undef('passari_web_ui_site_domain')}}"

passari_web_ui_venv_dir: "{{passari_packages_venvs_root}}/passari-web-ui"
passari_web_ui_lib_python_dir: >-
  {{passari_web_ui_venv_dir}}/lib/python{{passari_packages_python_version}}
passari_web_ui_src_dir: >-
  {{passari_web_ui_lib_python_dir}}/site-packages/passari_web_ui

passari_web_ui_static_root: "/usr/share/nginx/passari_web_ui_static"
passari_web_ui_uwsgi_socket_dir: "/var/local/passari/run"
passari_web_ui_uwsgi_socket_path: >-
  {{passari_web_ui_uwsgi_socket_dir}}/passari-web-ui.sock
passari_web_ui_uwsgi_processes: 2
passari_web_ui_uwsgi_stats_socket: >-
  {{passari_web_ui_uwsgi_socket_dir}}/passari-web-ui.stats.sock

passari_web_ui_secret_key: "{{undef('web_ui_secret_key')}}"
passari_web_ui_password_salt: "{{undef('web_ui_password_salt')}}"

passari_web_ui_dev_ssl_cert_dir: "/etc/pki/tls/certs"
passari_web_ui_dev_ssl_key_dir: "/etc/pki/tls/private"

passari_web_ui_heartbeat_interval_sync_processed_sips: "{{undef()}}"
passari_web_ui_heartbeat_interval_sync_objects: "{{undef()}}"
passari_web_ui_heartbeat_interval_sync_attachments: "{{undef()}}"
passari_web_ui_heartbeat_interval_sync_hashes: "{{undef()}}"
