---
- name: Install certbot
  yum:
    name: certbot
  tags:
    - museumplus-pas-web-ui
    - letsencrypt
  when: enable_letsencrypt

- name: Add certbot script
  template:
    src: "templates/generate_cert.sh.j2"
    dest: "/root/generate_cert_{{ site_domain }}.sh"
    mode: u+rx
  tags:
    - museumplus-pas-web-ui
    - letsencrypt
  when: enable_letsencrypt

- name: Generate SSL certificate
  command: "/root/generate_cert_{{ site_domain }}.sh"
  tags:
    - museumplus-pas-web-ui
    - letsencrypt
  notify:
    - "reload nginx config"
  when: enable_letsencrypt

- name: Add cron job for SSL certificate renewal
  cron:
    name: "Renew {{ site_domain }} Let's Encrypt certificate"
    job: "/root/generate_cert_{{ site_domain }}.sh"
    user: root
    # Pick a random minute to check renewal as recommended by Let's Encrypt
    minute: "{{ 60 | random }}"
    hour: 21
  tags:
    - museumplus-pas-web-ui
    - letsencrypt
  when: enable_letsencrypt
